name = "vemaint"
compatibility_date = "2024-10-22"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]
[vars]
AUTH_SECRET = "local-dev-auth-secret-please-change"

[[d1_databases]]
binding = "DB"
database_name = "vemaint"
database_id = "745ac509-c99d-4e9b-8620-44831093244e"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "R2"
bucket_name = "vemaint"

[[kv_namespaces]]
binding = "KV"
id = "934631cf47c84ab5b92f813fb8ec727d"
